dbname: "your_database"
user: "db_user"
password: "secure_password"
host: "localhost"
port: 5432
batch_size: 1000
max_connections: 5
min_connections: 1
retry_attempts: 3
enable_progress_tracking: true
enable_data_validation: true
timestamp_tolerance_seconds: 1.0
global_hash_exclude_columns: []
lock_timeout: 3600
auto_add_columns: true